name: TD's Tremendous Rips

on:
  workflow_dispatch:
    inputs:
      code:
        description: "Enter PowerShell Code"
        required: true

jobs:
  build:
    name: TD's Ripping Lab Running
    runs-on: windows-latest
    timeout-minutes: 999999

    steps:
    - name: Set PowerShell Code
      run: echo "INPUT_CODE=${{ inputs.code }}" >> $GITHUB_ENV

    - name: Downloading Pileburner Script...
      run: |
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Myiaggar/Pileburner/main/pileburner.ps1" -OutFile "pileburner.ps1"

    - name: Executing Pileburner Script...
      run: |
        powershell.exe -ExecutionPolicy Bypass -File pileburner.ps1

    - name: Keeping VM Alive...
      run: |
        while ($true) { Write-Host "VM Running..."; Start-Sleep -Seconds 60 }
